gensim_similarity_trainer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trainer/', include('trainer.urls'))
]

trainer/urls.py
from django.urls import path
from . import views

app_name = 'trainer'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('<str:input>/similarities/', views.similarities, name='similarities')
]

trainer/models.py
from django.db import models


# Create your models here.
class Documents(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=10000)

    def __str__(self):
        return self.title+'\n'+self.text

trainer/views.py
from django.http import HttpResponse, JsonResponse
from django.views import generic
from .models import Documents
from . import gsmutils


# Create your views here.
class Index(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'documents'
    queryset = Documents.objects.all


def similarities(request, input):
    document = Documents.objects.get(pk=input)

    tags = ['persona', 'tipo', 'materiale', 'animale']
    # This list of pairs will contain every word of document associated with the tag most similar to it
    similarity_pairs = []
    # Tokenizing document
    tokens = gsmutils.doc2tokens(document.text)
    # Getting model(rendere globale)
    model = gsmutils.load_w2vmodel(path='loaded C:\\Users\\simpl\\AppData\\Local\\Temp\\gensim-model-4vug4uqj')
    for token in tokens:
        most_similar_tag = gsmutils.most_similar_tag(model=model, input_word=token, tags=tags)
        similarity_pairs.append([token, most_similar_tag])

    json_document = {
        'title': document.title,
        'text': similarity_pairs
    }
    return JsonResponse(json_document)

templates/index.html
{% extends 'masterpage.html' %}
{% block content %}
<div id="app">
    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" style="padding-left: 26px">
                <i class="fas fa-align-left"></i>
            </a>
            <a class="navbar-item">
                <h1 class="card-header-title">
                    [[ title ]]
                </h1>
            </a>
        </div>
    </nav>

    <div class="columns">
        <div class="column hero is-3 is-fullheight has-background-white-ter">
            <div class="main" style="padding-top: 30px; padding-left: 30px">
                <aside class="menu">
                    <p class="menu-label">Documents</p>
                    <ul class="menu-list">
                        {% for document in documents %}
                        <li class="list-item">
                            <a onclick="showClick({{ document.id }})">{{ document.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>

                </aside>
            </div>
        </div>

        <div class="column is-two-thirds">
            <section class="hero">
                <div class="hero-body">
                    <p class="title">
                        Search
                    </p>
                    <form @submit="submitRequest" method="post">
                        <div class="field has-addons">
                            <div class="control">
                                <input class="input" type="text" placeholder="Insert word" v-model="input">
                            </div>
                            <button class="control button is-primary">
                                Submit
                            </button>
                        </div>
                    </form>
                    <br>
                        <article v-if="booleans.something_loaded" class="message">
                            <div class="message-header">
                                <p>[[ on_main_board_title ]]</p>
                            </div>
                            <div class="message-body">
                                [[ on_main_board_text ]]
                            </div>
                        </article>
                    <br>
                    <p class="content is-medium">[[ output ]]</p>
                </div>
            </section>
        </div>
    </div>
</div>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';

    Vue.component("main-board", {
        delimiters: ['[[', ']]'],
        props: ['title', 'text'],
        template: '<article class="message">' +
            '<div class="message-header">' +
            '<p>[[ title ]]</p>' +
            '</div>' +
            '<div class="message-body">' +
            '[[ text ]]' +
            '</div>' +
            '</article>'
    })

    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            title: 'Gensim Trainer',
            input: '',
            output: '',
            selected_document: 0,
            on_main_board_title: "",
            on_main_board_text: "",
            booleans: {
                something_loaded: false
            }
        },
        methods: {
            submitRequest(e) {
                e.preventDefault();
                let vue_obj = this;
                axios.post("{% url 'trainer:similarities' input="1" %}"
                    .replace("1", vue_obj.input))
            .then(response =>{
                    vue_obj.output = response.data
                })
                    .catch(error =>{
                        vue_obj.output = 'Some error occurred\n'+error;
                    })
            },
            loadDocument(e) {
                //e.preventDefault();
                let vue_obj = this;
                axios.post("{% url 'trainer:similarities' input="1" %}".
                replace("1", vue_obj.selected_document))
            .then(response =>{
                    vue_obj.booleans.something_loaded = true;
                    //vue_obj.output = 'Data received';
                    vue_obj.on_main_board_title = response.data['title'];
                    vue_obj.on_main_board_text = response.data['text'];

                    // Costruire documento caricato con tags Bulma
                })
                    .catch(response =>{

                    })
            }
        },
        watch: {
            selected_document: function () {
                this.loadDocument()
            }
        }
    })


    showClick = (document_id) => {
        app.selected_document = document_id
    }
</script>
{% endblock %}

templates/masterpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <style>
        .list-item a:hover{
            background-color: cornflowerblue;
            color: aliceblue;
        }
    </style>
    <title>Title</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>